name: Deploy to GCP
on:
  push:
    branches:
      - master

# Izin wajib agar GitHub bisa membuat token OIDC
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Google Auth (Keyless with Workload Identity Federation)
      id: auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: '${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
        service_account: '${{ secrets.GCP_SERVICE_ACCOUNT }}'

    # Setelah langkah otentikasi di atas berhasil, GitHub Actions Anda 
    # sudah memiliki akses ke Google Cloud seolah-olah ia adalah Service Account.
    # Anda bisa melanjutkan perintah gcloud, mengirim ke Cloud Build, atau deploy ke GKE.
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Test GCP Connection
      run: gcloud info